'use strict';
globalThis.GrowthUI = (() => {
  let tab = 'gear';
  const icon = name => `<i data-lucide="${name}"></i>`;
  function render(host, s, hooks) {
    const r = RPG.ensure(s), level = RPG.level(s), bonus = RPG.bonus(s);
    host.innerHTML = `<div class="growth-profile"><div class="host-portrait">旭<span>CHEN XU</span></div><div><span class="eyebrow">宿主档案 / ${['觉醒','初行','见习','熟练','进阶','精英','突破','共鸣'][level-1]}</span><h3>陈旭 <small>Lv.${level}</small></h3><div class="xp-track"><span style="width:${level===8?100:r.xp%100}%"></span></div><p>${level===8?'首章成长已满':r.xp%100+' / 100 EXP'} <span>探索 ${r.found.length} / 8</span></p></div></div><div class="growth-bonuses"><span>攻击 <b>+${bonus.attack}</b></span><span>生命 <b>+${bonus.hp}</b></span><span>格挡 <b>+${bonus.guard}</b></span><span>现金 <b>¥${s.stats.cash}</b></span></div><nav class="growth-tabs" aria-label="成长分类">${[['gear','装备','shirt'],['shop','后街补给','shopping-bag'],['finds','校园收藏','scan-search']].map(([id,label,i])=>`<button data-growth-tab="${id}" aria-selected="${tab===id}">${icon(i)}${label}</button>`).join('')}</nav><div id="growth-content"></div>`;
    const content = host.querySelector('#growth-content');
    if (tab === 'gear') {
      content.innerHTML = `<div class="equipment-slots">${Object.entries(RPG.slots).map(([slot,label])=>{const item=RPG.items[r.equipped[slot]];return `<div><span>${label}</span>${icon(item?.icon || 'plus')}<strong>${item?.name || '尚未装备'}</strong><small>${item?.desc || '可在后街补给购入'}</small></div>`;}).join('')}</div><h4 class="growth-section">随身装备 <span>${r.owned.length} / 6</span></h4><div class="gear-list">${r.owned.map(id=>{const item=RPG.items[id],equipped=r.equipped[item.slot]===id;return `<article class="gear-row ${item.rarity}"><div class="item-icon">${icon(item.icon)}</div><div><h4>${item.name}</h4><p>${item.desc}</p></div><button class="secondary" data-equip="${id}" ${s.active?'disabled':''}>${icon(equipped?'check':'plus')}${equipped?'卸下':'装备'}</button></article>`;}).join('')||'<p class="inventory-empty">背包里还没有装备。</p>'}</div><h4 class="growth-section">消耗品</h4><div class="supplies-row">${['coffee','notes'].map(id=>`<button class="secondary" data-use="${id}" ${s.active||!r.bag[id]?'disabled':''}>${icon(RPG.items[id].icon)}${RPG.items[id].name} × ${r.bag[id]}</button>`).join('')}</div>`;
    }
    if (tab === 'shop') content.innerHTML = `<div class="shop-banner"><span>BACKSTREET SUPPLY</span><h3>为下一次机会，做好准备。</h3><p>苏祁：“工具趁手，事情就成了一半。”</p></div><div class="shop-grid">${Object.entries(RPG.items).map(([id,item])=>{const owned=item.slot&&r.owned.includes(id);return `<article class="shop-item ${item.rarity||'supply'}"><div class="shop-top">${icon(item.icon)}<span>${item.slot?RPG.slots[item.slot]:'补给'}</span></div><h4>${item.name}</h4><p>${item.desc}</p><button class="secondary" data-buy="${id}" ${s.active||owned||s.stats.cash<item.price||!item.slot&&r.bag[id]>=9?'disabled':''}>${icon(owned?'check':'shopping-cart')}${owned?'已持有':'¥ '+item.price}</button></article>`;}).join('')}</div>`;
    if (tab === 'finds') content.innerHTML = `<p class="collection-lead">有些记忆，需要亲自走近。</p><div class="collection-grid">${Object.entries(RPG.finds).map(([id,item])=>{const found=r.found.includes(id);return `<article class="collection-item ${found?'found':'locked'}"><div>${icon(found?item.icon:'lock-keyhole')}<span>${CONTENT.places[id].name}</span></div><h4>${found?item.name:'未发现的记忆'}</h4><p>${found?item.text:'前往地点附近，调查留下的物件。'}</p><small>${found?'已归档':item.xp+' EXP'}</small></article>`;}).join('')}</div>`;
    host.querySelectorAll('[data-growth-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.growthTab;render(host,s,hooks);});
    for (const [key,fn] of [['buy',RPG.buy],['equip',RPG.equip],['use',RPG.use]]) host.querySelectorAll(`[data-${key}]`).forEach(b=>b.onclick=()=>{const id=b.dataset[key];if(fn(s,id)){hooks.save();hooks.hud();hooks.sound('win');render(host,s,hooks);}else hooks.toast('当前无法使用，进度已保留。');});
    hooks.icons();
  }
  return { render };
})();
